version: '2'
services:
  bonapphedi-app:
    image: bonapphedi
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://bonapphedi-mariadb:3306/bonapphedi
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  bonapphedi-mariadb:
    extends:
      file: mariadb.yml
      service: bonapphedi-mariadb
